<a href="https://colab.research.google.com/github/neerajgosai19/CONVOLUTIONAL-NEURAL-NETWORK/blob/master/RECURRENT_NETWORKS_IN_DEEP_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.2.0rc0

     |████████████████████████████████| 515.9MB 31kB/s 
     |████████████████████████████████| 3.9MB 39.4MB/s 
     |████████████████████████████████| 450kB 43.5MB/s 
  Found existing installation: tensorboard 2.3.0
    Uninstalling tensorboard-2.3.0:
      Successfully uninstalled tensorboard-2.3.0
  Found existing installation: tensorflow-estimator 2.3.0
    Uninstalling tensorflow-estimator-2.3.0:
      Successfully uninstalled tensorflow-estimator-2.3.0
  Found existing installation: tensorflow 2.3.0
    Uninstalling tensorflow-2.3.0:
      Successfully uninstalled tensorflow-2.3.0


In [8]:
import numpy as np
import tensorflow as tf
if not tf.__version__ == '2.2.0rc0':
  print (tf.__version__)
  
   


2.2.0-rc0


In [9]:
LSTM_CELL_SIZE = 4
state = (tf.zeros([1,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>)

In [10]:
LSTM = tf.keras.layers.LSTM(LSTM_CELL_SIZE, return_sequences= True , return_state= True)
LSTM.states=state
print(LSTM.states)

(<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0., 0., 0., 0.]], dtype=float32)>)


In [16]:
SAMPLE_INPUT = tf.constant([[2,3,4,3,2,3]],dtype=tf.float32)
batch_Size = 1
n_feature = 6
sentence_length = 1 
new_shape = (batch_Size , n_feature , sentence_length)
inputs = tf.constant(np.reshape(SAMPLE_INPUT, new_shape) , dtype= tf.float32)

In [18]:
output, final_memory_state, final_carry_state = LSTM(inputs)

In [19]:
print('Output : ', tf.shape(output))

print('Memory : ',tf.shape(final_memory_state))

print('Carry state : ',tf.shape(final_carry_state))

Output :  tf.Tensor([1 6 4], shape=(3,), dtype=int32)
Memory :  tf.Tensor([1 4], shape=(2,), dtype=int32)
Carry state :  tf.Tensor([1 4], shape=(2,), dtype=int32)
